version: "3.8"
services: 
  user-registration-service:
    image: danvi/user-registration-service:1.1
    restart: always
    build: .
    ports:
      - 8080:9999
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: dockeruser
      MYSQL_PASSWORD: DanviShanmuki@2
      MYSQL_DB: registration
      MYSQL_PORT: 3306
      SERVER_PORT: 9999
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: dockeruser
      MYSQL_PASSWORD: DanviShanmuki@2
      MYSQL_ROOT_PASSWORD: DanviShanmuki@2
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: